import React, { useEffect, useState } from 'react';
import jsPDF from 'jspdf';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import Sidebar from '../../components/Sidebar';
import StudentProfile from './studentprofile.jsx';

export default function StudentMarks() {
  const handleDownloadPDF = () => {
    if (marks.length === 0) {
      alert('No marks data available to export.');
      return;
    }

    try {
      const doc = new jsPDF('p', 'mm', 'a4');
      const pageWidth = doc.internal.pageSize.getWidth();
      let yPosition = 20;
      
      // Get student info
      const userRaw = localStorage.getItem('user');
      const user = userRaw ? JSON.parse(userRaw) : {};
      const studentName = user.fullName || user.userName || 'Student';
      
      // Header with background
      doc.setFillColor(67, 56, 202); // Indigo color
      doc.rect(0, 0, pageWidth, 40, 'F');
      
      // Title
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.text('STUDENT MARKS REPORT', pageWidth / 2, 15, { align: 'center' });
      
      // Student name
      doc.setFontSize(12);
      doc.text(`Student: ${studentName}`, pageWidth / 2, 25, { align: 'center' });
      
      // Date
      doc.setFontSize(10);
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, 32, { align: 'center' });
      
      yPosition = 50;
      
      // Reset text color
      doc.setTextColor(0, 0, 0);
      
      // Summary Statistics
      if (marks.length > 0) {
        const totalMarks = marks.reduce((sum, m) => sum + (parseInt(m.marks) || 0), 0);
        const averageMark = (totalMarks / marks.length).toFixed(1);
        const highestMark = Math.max(...marks.map(m => parseInt(m.marks) || 0));
        const passedSubjects = marks.filter(m => parseInt(m.marks) >= 50).length;
        
        // Statistics box
        doc.setFillColor(239, 246, 255);
        doc.rect(15, yPosition, pageWidth - 30, 25, 'F');
        doc.setDrawColor(59, 130, 246);
        doc.rect(15, yPosition, pageWidth - 30, 25, 'S');
        
        doc.setFontSize(12);
        doc.setTextColor(30, 64, 175);
        doc.text('SUMMARY STATISTICS', 20, yPosition + 8);
        
        doc.setFontSize(10);
        doc.setTextColor(55, 65, 81);
        doc.text(`Total Assessments: ${marks.length}`, 20, yPosition + 16);
        doc.text(`Average Mark: ${averageMark}%`, 20, yPosition + 21);
        doc.text(`Highest Mark: ${highestMark}%`, 100, yPosition + 16);
        doc.text(`Passed: ${passedSubjects}/${marks.length}`, 100, yPosition + 21);
        
        yPosition += 35;
      }
      
      // Table Header
      doc.setFontSize(14);
      doc.setTextColor(67, 56, 202);
      doc.text('MARKS DETAILS', 20, yPosition);
      yPosition += 10;
      
      // Table header background
      doc.setFillColor(67, 56, 202);
      doc.rect(15, yPosition, pageWidth - 30, 10, 'F');
      
      // Table headers
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(9);
      doc.text('#', 18, yPosition + 6);
      doc.text('Teacher', 30, yPosition + 6);
      doc.text('Subject', 70, yPosition + 6);
      doc.text('Exam', 110, yPosition + 6);
      doc.text('Mark', 140, yPosition + 6);
      doc.text('Date', 160, yPosition + 6);
      
      yPosition += 12;
      
      // Table rows
      doc.setTextColor(0, 0, 0);
      marks.forEach((mark, index) => {
        // Check if we need a new page
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        
        // Alternate row background
        if (index % 2 === 0) {
          doc.setFillColor(248, 250, 252);
          doc.rect(15, yPosition - 2, pageWidth - 30, 8, 'F');
        }
        
        // Row data
        doc.setFontSize(8);
        doc.text((index + 1).toString(), 18, yPosition + 4);
        doc.text((mark.teacher?.fullName || 'N/A').substring(0, 15), 30, yPosition + 4);
        doc.text((mark.teacher?.subject || 'N/A').substring(0, 15), 70, yPosition + 4);
        doc.text((mark.examType || 'N/A').substring(0, 10), 110, yPosition + 4);
        doc.text(`${mark.marks}%`, 140, yPosition + 4);
        doc.text(mark.date ? new Date(mark.date).toLocaleDateString() : 'N/A', 160, yPosition + 4);
        
        yPosition += 8;
      });
      
      // Footer
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(107, 114, 128);
        doc.text('Generated by Tutor App - Student Management System', pageWidth / 2, 285, { align: 'center' });
        doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, 290, { align: 'center' });
      }
      
      // Save the PDF
      const fileName = `student_marks_${studentName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF. Please try again. Error: ' + error.message);
    }
  };
  const [marks, setMarks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [teachers, setTeachers] = useState([]);
  const [selectedTeacher, setSelectedTeacher] = useState('');
  const [loadingTeachers, setLoadingTeachers] = useState(true);

  // Get student id from localStorage
  const getStudentId = () => {
    try {
      const userRaw = localStorage.getItem('user');
      if (userRaw) {
        const userObj = JSON.parse(userRaw);
        return userObj.id || userObj._id || '';
      }
    } catch {}
    return '';
  };

  const studentId = getStudentId();

  // Fetch teachers list
  useEffect(() => {
    fetch('http://localhost:5000/api/users?role=teacher')
      .then(res => res.json())
      .then(data => {
        setTeachers(data);
        setLoadingTeachers(false);
      })
      .catch(() => {
        setLoadingTeachers(false);
      });
  }, []);

  // Fetch marks based on selected teacher
  useEffect(() => {
    if (!studentId) {
      setLoading(false);
      return;
    }

    setLoading(true);
    const url = selectedTeacher
      ? `http://localhost:5000/api/marks/teacher/${selectedTeacher}/student/${studentId}`
      : `http://localhost:5000/api/marks/student/${studentId}`;

    fetch(url)
      .then(res => res.json())
      .then(data => {
        setMarks(data);
        setLoading(false);
      })
      .catch(error => {
        console.error('Error fetching marks:', error);
        setLoading(false);
      });
  }, [studentId, selectedTeacher]);

  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-br from-blue-200 via-purple-200 to-pink-200">
      <Header />
      <div className="flex flex-row flex-grow">
        <Sidebar role="student" />
        <div className="flex flex-col items-center justify-center flex-grow py-8">
           
          <div className="w-full max-w-2xl p-8 shadow-xl bg-white/90 rounded-2xl">
            <StudentProfile />
            <h2 className="mb-6 text-3xl font-extrabold text-center text-transparent bg-clip-text bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 drop-shadow-lg">My Marks</h2>
            <div className="flex flex-col gap-2 mb-6 md:flex-row md:items-center md:justify-between">
              <div className="flex-1">
                <label htmlFor="teacher" className="block mb-2 text-sm font-medium text-gray-700">
                  Filter by Teacher
                </label>
                <select
                  id="teacher"
                  value={selectedTeacher}
                  onChange={(e) => setSelectedTeacher(e.target.value)}
                  className="block w-full py-2 pl-3 pr-10 mt-1 text-base border-gray-300 rounded-md focus:outline-none focus:ring-purple-500 focus:border-purple-500 sm:text-sm"
                  disabled={loadingTeachers}
                >
                  <option value="">All Teachers</option>
                  {teachers.map((teacher) => (
                    <option key={teacher._id} value={teacher._id}>
                      {teacher.fullName} - {teacher.subject}
                    </option>
                  ))}
                </select>
              </div>
              <button
                className="px-5 py-2 font-bold text-white transition-all shadow bg-gradient-to-r from-red-500 to-orange-500 rounded-xl hover:scale-105"
                onClick={handleDownloadPDF}
                disabled={marks.length === 0}
              >
                📄 Download PDF Report
              </button>
            </div>

            {loading ? (
              <div className="text-lg text-gray-600">Loading...</div>
            ) : marks.length === 0 ? (
              <div className="text-lg text-gray-600">No marks found.</div>
            ) : (
              <table className="w-full mt-4 text-center">
                <thead>
                  <tr className="text-purple-600">
                    <th className="py-2">Teacher</th>
                    <th className="py-2">Subject</th>
                    <th className="py-2">Exam Type</th>
                    <th className="py-2">Marks</th>
                    <th className="py-2">Date</th>
                    <th className="py-2">Note</th>
                  </tr>
                </thead>
                <tbody>
                  {marks.map((m, i) => (
                    <tr key={m._id || i} className="hover:bg-purple-50">
                      <td className="py-2">{m.teacher?.fullName || 'N/A'}</td>
                      <td className="py-2">{m.teacher?.subject || 'N/A'}</td>
                      <td className="py-2">{m.examType}</td>
                      <td className="py-2">{m.marks}</td>
                      <td className="py-2">{new Date(m.date).toLocaleDateString()}</td>
                      <td className="py-2">{m.specialNote}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
